# Generated by Django 6.0.6 on 2026-07-07 09:47

import apps.common.mixins.mediafolder
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('california_king', 'California King'), ('bunk_bed', 'Bunk bed'), ('sofa', 'Sofa'), ('pull_out_sofa', 'Pull-out sofa'), ('futon', 'Futon'), ('adjustable_bed', 'Adjustable bed')], default='single', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('bedrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('bathrooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('max_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not available'), ('under_maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
            bases=(apps.common.mixins.mediafolder.MediaOwnerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('house', 'House')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_renovation', 'Renovations in progress')], default='active', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='property.amenity')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
            bases=(apps.common.mixins.mediafolder.MediaOwnerMixin, models.Model),
        ),
    ]
