# Generated by Django 6.0.6 on 2026-07-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_room_number_per_property',
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('property', 'room_number'), name='unique_room_number_per_property'),
        ),
    ]
