# Generated by Django 6.0.6 on 2026-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_unit_unique_room_number_per_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='review_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
