# Generated by Django 6.0.6 on 2026-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4),
        ),
    ]
