# Generated by Django 6.0.6 on 2026-07-17 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_amenity_icon_amenity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
