# Generated by Django 6.0.6 on 2026-07-19 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_bed_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='property',
            name='unique_property_street_house_number_postal_code',
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('street', 'house_number', 'postal_code', 'floor'), name='unique_property_street_house_number_postal_code_floor'),
        ),
    ]
