# Generated by Django 6.0.6 on 2026-07-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property'),
        ),
        migrations.AddField(
            model_name='unitimage',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_images', to='media.media'),
        ),
        migrations.AddField(
            model_name='unitimage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.unit'),
        ),
        migrations.AddField(
            model_name='useravatar',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
    ]
