# Generated by Django 6.0.6 on 2026-07-16 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_initial'),
        ('property', '0006_remove_amenity_icon_amenity_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amenity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='property.amenity')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_icon', to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
